import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getService,getServices } from "@/lib/content-store";

export const dynamic="force-dynamic";
export async function generateMetadata({params}:PageProps<"/services/[slug]">):Promise<Metadata>{const s=await getService((await params).slug);return s?{title:`${s.title} | UtiliTech`,description:s.short}:{}}
export default async function ServicePage({params}:PageProps<"/services/[slug]">){const s=await getService((await params).slug);if(!s)notFound();const related=(await getServices()).filter(x=>x.category===s.category&&x.slug!==s.slug).slice(0,3);return <main className="nsx-site">
  <header className="nsx-header"><Link className="brand" href="/"><Image className="brand-logo" src="/logo-mark.svg" alt="" width={34} height={34} priority/><span>UTILITECH</span></Link><nav className="nsx-nav"><Link href="/#services">Services</Link><Link href="/#process">Process</Link><Link href="/#why">Why us</Link><Link href="/#contact">Contact</Link></nav><Link className="nsx-head-cta" href="/#contact">Get a proposal <span>↗</span></Link></header>
  <section className="nsx-service-hero"><div><span className="nsx-label">HOME / SERVICES / {s.category.toUpperCase()}</span><h1>{s.title}</h1><p>{s.short}</p><Link className="button button-primary" href="/#contact">Discuss this service <span>→</span></Link></div><div className="nsx-service-console"><div><span>UTILITECH / SERVICE</span><b>● READY</b></div><small>{s.category}</small><strong>{s.title}</strong><div className="nsx-console-lines"><i/><i/><i/><i/><i/></div><p>STRATEGY → BUILD → LAUNCH</p></div></section>
  <section className="nsx-section nsx-overview"><div><span className="nsx-label">01 / OVERVIEW</span><h2>Built around the <em>outcome.</em></h2></div><div><p>{s.intro}</p><h3>WHAT THIS HELPS YOU ACHIEVE</h3>{s.benefits.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</article>)}</div></section>
  <section className="nsx-popular"><div className="nsx-section"><div className="nsx-heading"><div><span className="nsx-label">02 / DELIVERABLES</span><h2>A clear path to <em>launch.</em></h2></div><p>Every engagement is shaped to the business, but the important stages always stay visible.</p></div><div className="nsx-deliverables">{s.deliverables.map((item,index)=><article key={item}><span>{String(index+1).padStart(2,"0")}</span><h3>{item}</h3><p>Planned, reviewed and delivered around your audience and goals.</p></article>)}</div></div></section>
  <section className="nsx-section"><div className="nsx-heading"><div><span className="nsx-label">03 / RELATED</span><h2>Useful services to <em>connect.</em></h2></div></div><div className="nsx-related">{related.map(item=><Link href={`/services/${item.slug}`} key={item.slug}><span>{item.category}</span><h3>{item.title}</h3><p>{item.short}</p><b>Explore <i>↗</i></b></Link>)}</div></section>
  <section className="nsx-service-cta"><span>READY TO MOVE?</span><h2>Turn the idea into a clear digital plan.</h2><Link className="button button-primary" href="/#contact">Request a proposal →</Link></section>
  <footer className="nsx-footer"><div><Link className="brand" href="/"><Image className="brand-logo" src="/logo-mark.svg" alt="" width={34} height={34}/><span>UTILITECH</span></Link><p>Web, application and digital growth services for ambitious teams.</p></div><div><b>EXPLORE</b><Link href="/#services">All services</Link><Link href="/#process">Process</Link></div><div><b>CONTACT</b><a href="tel:+919653127760">+91 96531 27760</a><a href="mailto:utilipayhub@gmail.com">utilipayhub@gmail.com</a></div><small>© 2026 UtiliTech</small></footer>
</main>}
