import Link from "next/link";
import LeadForm from "./lead-form";
import { getServices,getSiteSettings } from "@/lib/content-store";
import { UtiliFooter, UtiliHeader } from "./site-chrome";

const featured = ["website-design","website-development","seo","custom-web-applications","ecommerce-websites","web-hosting"];

export const dynamic="force-dynamic";
export default async function Home(){const all=await getServices(),settings=await getSiteSettings();const featuredServices=featured.map(slug=>all.find(service=>service.slug===slug)).filter(service=>service!==undefined);return <main className="nsx-site">
  <UtiliHeader services={all}/>

  <section className="nsx-hero">
    <div className="nsx-hero-copy nsx-enter"><span className="nsx-eyebrow"><i/> COMPLETE DIGITAL SERVICES FOR GROWING BUSINESSES</span><h1>We build your business for the <em>web.</em></h1><p>Strategy, design, development and marketing in one connected team—from your first website to the systems, campaigns and infrastructure behind it.</p><div className="nsx-actions"><Link className="button button-primary" href="/contact">Start a project <span>→</span></Link><Link className="button button-ghost" href="/services">View all services</Link></div><div className="nsx-trust"><span>Original design</span><span>Mobile ready</span><span>Built to scale</span></div></div>
    <div className="nsx-command nsx-enter" aria-label="UtiliTech service dashboard"><div className="nsx-command-top"><span>UTILITECH / CAPABILITIES</span><b>● ONLINE</b></div><div className="nsx-command-title"><small>THE FULL DIGITAL STACK</small><strong>Everything<br/>connected.</strong></div><div className="nsx-command-grid"><span><b>01</b>DESIGN</span><span><b>02</b>DEVELOP</span><span><b>03</b>GROW</span><span><b>04</b>HOST</span></div><div className="nsx-pulse"><i/><i/><i/><i/><i/></div></div>
  </section>

  <section className="nsx-signal"><p>One team from idea to launch and beyond.</p><div><strong>23</strong><span>specialist services</span></div><div><strong>05</strong><span>connected capabilities</span></div><div><strong>100%</strong><span>responsive delivery</span></div></section>

  <section className="nsx-section nsx-home-services" id="services"><div className="nsx-heading"><div><span className="nsx-label">01 / CHOOSE YOUR STARTING POINT</span><h2>Turn a business need into a clear <em>next step.</em></h2></div><p>Pick the outcome closest to where you are now. We&apos;ll connect it to the right service and a transparent starting price.</p></div><div className="nsx-start-grid"><Link href="/services#design-development"><span>01 / LAUNCH OR REDESIGN</span><h3>Build a credible digital home.</h3><p>Brand, website and conversion-focused development for a confident first impression.</p><b>Explore web services ↗</b></Link><Link href="/services#internet-marketing"><span>02 / FIND MORE CUSTOMERS</span><h3>Grow useful attention.</h3><p>Search, paid and social campaigns connected to measurable business goals.</p><b>Explore growth services ↗</b></Link><Link href="/services#application-development"><span>03 / IMPROVE A PROCESS</span><h3>Turn manual work into a system.</h3><p>Custom applications, commerce and management tools shaped around real workflows.</p><b>Explore application services ↗</b></Link></div><Link className="button button-primary" href="/services">Compare every service →</Link></section>

  <section className="nsx-popular"><div className="nsx-section"><div className="nsx-heading"><div><span className="nsx-label">02 / MOST REQUESTED</span><h2>High-impact places to <em>begin.</em></h2></div><p>Focused offers for the moments businesses face most often: launching, modernising, finding customers and selling online.</p></div><div className="nsx-cards">{featuredServices.map((s,index)=><Link href={`/services/${s.slug}`} key={s.slug}><span>{String(index+1).padStart(2,"0")} — {s.category}</span><h3>{s.title}</h3><p>{s.short}</p><b>View capability <i>↗</i></b></Link>)}</div></div></section>

  <section className="nsx-section" id="process"><div className="nsx-heading"><div><span className="nsx-label">03 / DELIVERY SYSTEM</span><h2>Four steps.<br/><em>No mystery.</em></h2></div><p>You always know what is being decided, what comes next and where your feedback matters.</p></div><div className="nsx-process"><article><span>01</span><div><h3>Discover</h3><p>Business, audience, objectives and the current digital setup.</p></div></article><article><span>02</span><div><h3>Define</h3><p>Structure, features, content needs, fixed scope and milestones.</p></div></article><article><span>03</span><div><h3>Build</h3><p>Visible design and development progress with planned reviews.</p></div></article><article><span>04</span><div><h3>Launch</h3><p>Cross-device testing, careful release, access and clear handover.</p></div></article></div></section>

  <section className="nsx-why" id="why"><div className="nsx-section nsx-why-grid"><div><span className="nsx-label">04 / WHY UTILITECH</span><h2>Technology is only useful when the business feels the <em>difference.</em></h2></div><div><article><b>A</b><h3>Business before features</h3><p>Every page and feature earns its place against a real goal.</p></article><article><b>B</b><h3>Custom, not recycled</h3><p>Your website and identity are shaped around your actual audience.</p></article><article><b>C</b><h3>Built for every screen</h3><p>Mobile experience, speed and clarity are considered from day one.</p></article><article><b>D</b><h3>Ready for the next stage</h3><p>Content controls, new services and payments can be added cleanly.</p></article></div></div></section>

  <section className="nsx-contact" id="contact"><div className="nsx-section nsx-contact-grid"><div><span className="nsx-label">05 / START HERE</span><h2>What should your digital presence do <em>better?</em></h2><p>Tell us the goal in plain language. We&apos;ll help identify the right service and turn it into a clear proposal.</p><div className="nsx-direct"><a href={`tel:${settings.phone.replace(/\s/g,"")}`}><span>CALL / WHATSAPP</span><strong>{settings.phone}</strong></a><a href={`mailto:${settings.email}`}><span>EMAIL</span><strong>{settings.email}</strong></a></div></div><LeadForm whatsapp={settings.whatsapp}/></div></section>

  <UtiliFooter/>
</main>}
