import Image from "next/image";
import Link from "next/link";
import LeadForm from "./lead-form";
import { serviceGroups } from "./service-data";
import { getServices } from "@/lib/content-store";

const featured = ["website-design","website-development","seo","custom-web-applications","ecommerce-websites","web-hosting"];

export const dynamic="force-dynamic";
export default async function Home(){const all=await getServices();const known=new Set(serviceGroups.map(group=>group.title));const groups=[...serviceGroups.map(group=>({...group,services:all.filter(service=>service.category===group.title)})),...Array.from(new Set(all.filter(service=>!known.has(service.category)).map(service=>service.category))).map((category,index)=>({number:String(serviceGroups.length+index+1).padStart(2,"0"),title:category,description:"Additional specialist services configured for your business.",services:all.filter(service=>service.category===category)}))].filter(group=>group.services.length);const featuredServices=featured.map(slug=>all.find(service=>service.slug===slug)).filter(service=>service!==undefined);return <main className="nsx-site">
  <header className="nsx-header" id="top"><Link className="brand" href="/"><Image className="brand-logo" src="/logo-mark.svg" alt="" width={34} height={34} priority/><span>UTILITECH</span></Link><nav className="nsx-nav"><a href="#services">Services</a><a href="#process">Process</a><a href="#why">Why us</a><a href="#contact">Contact</a></nav><a className="nsx-head-cta" href="#contact">Get a proposal <span>↗</span></a></header>

  <section className="nsx-hero">
    <div className="nsx-hero-copy nsx-enter"><span className="nsx-eyebrow"><i/> COMPLETE DIGITAL SERVICES FOR GROWING BUSINESSES</span><h1>We build your business for the <em>web.</em></h1><p>Strategy, design, development and marketing in one connected team—from your first website to the systems, campaigns and infrastructure behind it.</p><div className="nsx-actions"><a className="button button-primary" href="#contact">Start a project <span>→</span></a><a className="button button-ghost" href="#services">View all services</a></div><div className="nsx-trust"><span>Original design</span><span>Mobile ready</span><span>Built to scale</span></div></div>
    <div className="nsx-command nsx-enter" aria-label="UtiliTech service dashboard"><div className="nsx-command-top"><span>UTILITECH / CAPABILITIES</span><b>● ONLINE</b></div><div className="nsx-command-title"><small>THE FULL DIGITAL STACK</small><strong>Everything<br/>connected.</strong></div><div className="nsx-command-grid"><span><b>01</b>DESIGN</span><span><b>02</b>DEVELOP</span><span><b>03</b>GROW</span><span><b>04</b>HOST</span></div><div className="nsx-pulse"><i/><i/><i/><i/><i/></div></div>
  </section>

  <section className="nsx-signal"><p>One team from idea to launch and beyond.</p><div><strong>23</strong><span>specialist services</span></div><div><strong>05</strong><span>connected capabilities</span></div><div><strong>100%</strong><span>responsive delivery</span></div></section>

  <section className="nsx-section" id="services"><div className="nsx-heading"><div><span className="nsx-label">01 / CAPABILITIES</span><h2>One brief.<br/><em>Every digital move.</em></h2></div><p>Start with the exact service you need. When the job grows, the strategy, creative, technology and infrastructure are already designed to work together.</p></div><div className="nsx-groups">{groups.map(group=><article key={group.title}><div className="nsx-group-head"><span>{group.number}</span><div><h3>{group.title}</h3><p>{group.description}</p></div></div><div className="nsx-link-grid">{group.services.map(service=><Link href={`/services/${service.slug}`} key={service.slug}>{service.title}<span>↗</span></Link>)}</div></article>)}</div></section>

  <section className="nsx-popular"><div className="nsx-section"><div className="nsx-heading"><div><span className="nsx-label">02 / MOST REQUESTED</span><h2>High-impact places to <em>begin.</em></h2></div><p>Focused offers for the moments businesses face most often: launching, modernising, finding customers and selling online.</p></div><div className="nsx-cards">{featuredServices.map((s,index)=><Link href={`/services/${s.slug}`} key={s.slug}><span>{String(index+1).padStart(2,"0")} — {s.category}</span><h3>{s.title}</h3><p>{s.short}</p><b>View capability <i>↗</i></b></Link>)}</div></div></section>

  <section className="nsx-section" id="process"><div className="nsx-heading"><div><span className="nsx-label">03 / DELIVERY SYSTEM</span><h2>Four steps.<br/><em>No mystery.</em></h2></div><p>You always know what is being decided, what comes next and where your feedback matters.</p></div><div className="nsx-process"><article><span>01</span><div><h3>Discover</h3><p>Business, audience, objectives and the current digital setup.</p></div></article><article><span>02</span><div><h3>Define</h3><p>Structure, features, content needs, fixed scope and milestones.</p></div></article><article><span>03</span><div><h3>Build</h3><p>Visible design and development progress with planned reviews.</p></div></article><article><span>04</span><div><h3>Launch</h3><p>Cross-device testing, careful release, access and clear handover.</p></div></article></div></section>

  <section className="nsx-why" id="why"><div className="nsx-section nsx-why-grid"><div><span className="nsx-label">04 / WHY UTILITECH</span><h2>Technology is only useful when the business feels the <em>difference.</em></h2></div><div><article><b>A</b><h3>Business before features</h3><p>Every page and feature earns its place against a real goal.</p></article><article><b>B</b><h3>Custom, not recycled</h3><p>Your website and identity are shaped around your actual audience.</p></article><article><b>C</b><h3>Built for every screen</h3><p>Mobile experience, speed and clarity are considered from day one.</p></article><article><b>D</b><h3>Ready for the next stage</h3><p>Content controls, new services and payments can be added cleanly.</p></article></div></div></section>

  <section className="nsx-contact" id="contact"><div className="nsx-section nsx-contact-grid"><div><span className="nsx-label">05 / START HERE</span><h2>What should your digital presence do <em>better?</em></h2><p>Tell us the goal in plain language. We&apos;ll help identify the right service and turn it into a clear proposal.</p><div className="nsx-direct"><a href="tel:+919653127760"><span>CALL / WHATSAPP</span><strong>+91 96531 27760</strong></a><a href="mailto:utilipayhub@gmail.com"><span>EMAIL</span><strong>utilipayhub@gmail.com</strong></a></div></div><LeadForm/></div></section>

  <footer className="nsx-footer"><div><Link className="brand" href="#top"><Image className="brand-logo" src="/logo-mark.svg" alt="" width={34} height={34}/><span>UTILITECH</span></Link><p>Web, application and digital growth services for ambitious teams.</p></div><div><b>EXPLORE</b><a href="#services">Services</a><a href="#process">Process</a><a href="#contact">Get a proposal</a></div><div><b>LEGAL</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><small>© 2026 UtiliTech · utilitech.in</small></footer>
  <a className="nsx-whatsapp" href="https://wa.me/919653127760?text=Hi%20UtiliTech%2C%20I%27d%20like%20to%20discuss%20a%20digital%20project." target="_blank" rel="noopener noreferrer"><span>●</span> WhatsApp</a>
</main>}
