"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { changeAdminPassword,clearAdminSession,createAdminSession,credentialsMatch,isAdminAuthenticated } from "@/lib/admin-auth";
import { contentStoreIsConfigured,getServices,saveServices } from "@/lib/content-store";
import type { Service } from "../service-data";
function value(data:FormData,key:string){return String(data.get(key)??"").trim()} function lines(data:FormData,key:string){return value(data,key).split("\n").map(x=>x.trim()).filter(Boolean).slice(0,12)} function normaliseSlug(input:string){return input.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function fromForm(data:FormData):Service{const service={slug:normaliseSlug(value(data,"slug")),title:value(data,"title"),category:value(data,"category"),short:value(data,"short"),intro:value(data,"intro"),benefits:lines(data,"benefits"),deliverables:lines(data,"deliverables")};if(!service.slug||!service.title||!service.category||service.short.length<10||service.intro.length<20||!service.benefits.length||!service.deliverables.length)throw new Error("Please complete every field with useful content.");return service}
async function requireAdmin(){if(!(await isAdminAuthenticated()))redirect("/admin?error=session");if(!contentStoreIsConfigured())redirect("/admin?error=storage")}
export async function loginAction(data:FormData){const email=value(data,"email").toLowerCase();if(!(await credentialsMatch(email,value(data,"password"))))redirect("/admin?error=login");await createAdminSession(email);redirect("/admin")}
export async function logoutAction(){await clearAdminSession();redirect("/admin")}
export async function changePasswordAction(data:FormData){await requireAdmin();const currentPassword=value(data,"currentPassword"),newPassword=value(data,"newPassword"),confirmPassword=value(data,"confirmPassword");if(newPassword.length<12||newPassword.length>128)redirect("/admin?error=password_length");if(newPassword!==confirmPassword)redirect("/admin?error=password_match");if(newPassword===currentPassword)redirect("/admin?error=password_same");if(!(await changeAdminPassword(currentPassword,newPassword)))redirect("/admin?error=password_current");await clearAdminSession();redirect("/admin?status=password")}
export async function createServiceAction(data:FormData){await requireAdmin();const service=fromForm(data),all=await getServices();if(all.some(x=>x.slug===service.slug))redirect("/admin?error=duplicate");await saveServices([...all,service]);revalidatePath("/");revalidatePath(`/services/${service.slug}`);redirect("/admin?status=created")}
export async function updateServiceAction(data:FormData){await requireAdmin();const oldSlug=value(data,"oldSlug"),service=fromForm(data),all=await getServices();if(all.some(x=>x.slug===service.slug&&x.slug!==oldSlug))redirect("/admin?error=duplicate");await saveServices(all.map(x=>x.slug===oldSlug?service:x));revalidatePath("/");revalidatePath(`/services/${oldSlug}`);revalidatePath(`/services/${service.slug}`);redirect("/admin?status=saved")}
export async function deleteServiceAction(data:FormData){await requireAdmin();const slug=value(data,"slug");if(value(data,"confirm")!==slug)redirect("/admin?error=confirm");await saveServices((await getServices()).filter(x=>x.slug!==slug));revalidatePath("/");revalidatePath(`/services/${slug}`);redirect("/admin?status=deleted")}
