"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { changeAdminPassword,clearAdminSession,createAdminSession,credentialsMatch,isAdminAuthenticated } from "@/lib/admin-auth";
import { contentStoreIsConfigured,getServices,saveServices,saveSiteSettings } from "@/lib/content-store";
import type { Service } from "../service-data";
function value(data:FormData,key:string){return String(data.get(key)??"").trim()} function lines(data:FormData,key:string){return value(data,key).split("\n").map(x=>x.trim()).filter(Boolean).slice(0,12)} function normaliseSlug(input:string){return input.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
function packagesFromForm(data:FormData){const ids=data.getAll("packageId"),names=data.getAll("packageName"),headings=data.getAll("packageHeading"),descriptions=data.getAll("packageDescription"),prices=data.getAll("packagePrice"),features=data.getAll("packageFeatures");return names.map((entry,index)=>({id:normaliseSlug(String(ids[index]??entry))||`package-${index+1}`,name:String(entry).trim(),heading:String(headings[index]??"").trim(),description:String(descriptions[index]??"").trim(),price:Number(prices[index]??0),features:String(features[index]??"").split("\n").map(item=>item.trim()).filter(Boolean).slice(0,16)}))}
function fromForm(data:FormData):Service{const service={slug:normaliseSlug(value(data,"slug")),title:value(data,"title"),category:value(data,"category"),short:value(data,"short"),intro:value(data,"intro"),benefits:lines(data,"benefits"),deliverables:lines(data,"deliverables"),price:Number(value(data,"price")),packages:packagesFromForm(data)};if(!service.slug||!service.title||!service.category||service.short.length<10||service.intro.length<20||!service.benefits.length||!service.deliverables.length||!Number.isFinite(service.price)||service.price<0||service.packages.some(item=>!item.name||!item.heading||item.description.length<10||!Number.isFinite(item.price)||item.price<0||!item.features.length))throw new Error("Please complete every field with useful content.");return service}
async function requireAdmin(){if(!(await isAdminAuthenticated()))redirect("/admin?error=session");if(!contentStoreIsConfigured())redirect("/admin?error=storage")}
export async function loginAction(data:FormData){const email=value(data,"email").toLowerCase();if(!(await credentialsMatch(email,value(data,"password"))))redirect("/admin?error=login");await createAdminSession(email);redirect("/admin")}
export async function logoutAction(){await clearAdminSession();redirect("/admin")}
export async function changePasswordAction(data:FormData){await requireAdmin();const currentPassword=value(data,"currentPassword"),newPassword=value(data,"newPassword"),confirmPassword=value(data,"confirmPassword");if(newPassword.length<12||newPassword.length>128)redirect("/admin?error=password_length");if(newPassword!==confirmPassword)redirect("/admin?error=password_match");if(newPassword===currentPassword)redirect("/admin?error=password_same");if(!(await changeAdminPassword(currentPassword,newPassword)))redirect("/admin?error=password_current");await clearAdminSession();redirect("/admin?status=password")}
export async function createServiceAction(data:FormData){await requireAdmin();const service=fromForm(data),all=await getServices();if(all.some(x=>x.slug===service.slug))redirect("/admin?error=duplicate");await saveServices([...all,service]);revalidatePath("/");revalidatePath(`/services/${service.slug}`);redirect("/admin?status=created")}
export async function updateServiceAction(data:FormData){await requireAdmin();const oldSlug=value(data,"oldSlug"),service=fromForm(data),all=await getServices();if(all.some(x=>x.slug===service.slug&&x.slug!==oldSlug))redirect("/admin?error=duplicate");await saveServices(all.map(x=>x.slug===oldSlug?service:x));revalidatePath("/");revalidatePath(`/services/${oldSlug}`);revalidatePath(`/services/${service.slug}`);redirect("/admin?status=saved")}
export async function deleteServiceAction(data:FormData){await requireAdmin();const slug=value(data,"slug");if(value(data,"confirm")!==slug)redirect("/admin?error=confirm");await saveServices((await getServices()).filter(x=>x.slug!==slug));revalidatePath("/");revalidatePath(`/services/${slug}`);redirect("/admin?status=deleted")}
export async function updateSettingsAction(data:FormData){await requireAdmin();await saveSiteSettings({phone:value(data,"phone"),email:value(data,"email"),whatsapp:value(data,"whatsapp").replace(/\D/g,""),address:value(data,"address"),legalName:value(data,"legalName"),registrationDate:value(data,"registrationDate"),cin:value(data,"cin"),gst:value(data,"gst")});revalidatePath("/","layout");redirect("/admin?status=settings")}
